FROM alpine:latest

RUN apk update
RUN apk add --no-cache python3-dev
RUN apk add --no-cache py3-pip
RUN pip3 install --upgrade pip

EXPOSE 5000

ENV FLASK_APP=router.py

WORKDIR /app

COPY requirements.txt .

RUN pip install -r requirements.txt

COPY router.py .

ENTRYPOINT [ "python" ]
CMD [ "router.py"]