FROM alpine:latest

RUN apk update
RUN apk add --no-cache openjdk11
RUN apk add --no-cache python3-dev
RUN apk add --no-cache py3-pip
RUN pip3 install --upgrade pip
RUN pip3 install flask

EXPOSE 5000

ENV FLASK_APP=router.py

WORKDIR /app
COPY api.py .
COPY executor.py .

CMD [ "python3", "api.py" ]